# Main page title
title: "Color Picker"

# Your name
name: "Igor Kowalczyk"

# Contact E-Mail (Public!)
email: "xxmajonezxx@gmail.com"

# Description
description: "A tool to help with the colors on the web."

# Base url (Not link! Only dir.
baseurl: "/color-picker"

# Support to mobile browsers (Itâ€™s unknown what range of browsers support this meta tags) [Better to set the value to "false"!]
mobile: "false"

# Twitter username (no link) - if you don't have - leave blank
twitter: "@majonezexe"

# Github username (no link) - if you don't have - leave blank
github_username:  "igorkowalczyk"

# First Launch of the site (displays in footer)
first-launch: "2019"

# Timezone
timezone: "Europe/Warsaw"

# Encoding (default: utf-8)
encoding: utf-8

# Markdown and Default theme
markdown: kramdown
theme: minima

# Exclude files
exclude:
 - Gemfile
 - Gemfile.lock

# Tracking id - if you don't have - leave blank
tracking_id: "UA-174454816-1"

# Verification ID - if you don't have - leave blank
verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY"
